# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Github_Portfolio/Shrinking_Layer_19.1/Shrinking_Layer_19.1.srcs/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xci
# IP: The module: 'shrink_fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github_Portfolio/Shrinking_Layer_19.1/Shrinking_Layer_19.1.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Github_Portfolio/Shrinking_Layer_19.1/Shrinking_Layer_19.1.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Github_Portfolio/Shrinking_Layer_19.1/Shrinking_Layer_19.1.srcs/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xci
# IP: The module: 'shrink_fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github_Portfolio/Shrinking_Layer_19.1/Shrinking_Layer_19.1.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Github_Portfolio/Shrinking_Layer_19.1/Shrinking_Layer_19.1.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
