# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/bin/zcu102.xdc

# IP: ip/shrink_dsp_macro_1/shrink_dsp_macro_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shrink_dsp_macro_1 || ORIG_REF_NAME==shrink_dsp_macro_1} -quiet] -quiet
